export const TYPOGRAPHY_TYPE = {
  MAIN_TITLE: "mainTitle",
  MAIN_REGULAR: "main",
  SUB_BOLD: "subTitle",
  SUB_REGULAR: "sub",
  BODY_BOLD: "bodyTitle",
  BODY_REGULAR: "body",
  CAPTION_BOLD: "captionTitle",
  CAPTION_REGULAR: "caption",
  LABEL_BOLD: "labelTitle",
  LABEL_REGULAR: "label",
} as const;

export const COLOR = {
  PRIMARY: "primary",
  PRIMARY_ACTIVE: "primaryActive",
  SECONDARY: "secondary",
  ERROR: "error",
  SUCCESS: "success",
  WARNING: "warning",
  INFO: "info",
  WHITE: "white",
  BLACK: "black",
  PURE_WHITE: "pureWhite",
  PRIMARY2: "primary2",
  GRAYLIGHT: "grayLight",
  GRAYDARK: "grayDark",
  BASE: "base",
  ACTIVE: "active",
  INACTIVE: "inactive",
  REVERSE: "reverse",
  SELECTED: "selected",
  UNSELECTED: "unselected",
  DEFAULT: "default",
} as const;
